function plotTrotLocalConnWOGaits( i, removeVecFcolFlag )
    %PLOTTROTLOCALCONN plot the local connection vector field for a trot
    %gait. 'i' is the sprawl index, or the body configuration for which the
    %gait is constructed.
    
    % if no information provide, keep the distinct colors for vector fields
    % on each stance phase
    if nargin < 2
        removeVecFcolFlag = false;
    end

    % load the data for plotting
    load('Data\Sinusoidal Gaits\clariConnVecF.mat');

    % if the vector field colors are requested to be removed, use black,
    % else saturate vector field colors to white
    switch removeVecFcolFlag
        case 1
            % black out the vector field
            col13s = zeros(1, 3); col24s = col13s;
        case 0
            % use the standard colors
            col13s = col13; col24s = col24;
    end

    % plot the local connection vector fields
    % ... plot it in 2 cols for each contact state
    fS = 12; 
    % 
    f = figure('units', 'pixels', 'position', [3200 -300 600 900]); 
    set(f,'Visible','on');
    tl = tiledlayout(f, 3, 2, "TileSpacing", "tight", "Padding", "tight");
    % %
    ax = nexttile(tl); % Ax for stance 13
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_13_X{i}, nAv_13_X{i}, ...
        "LineWidth", lW_Vector, "Color", col13s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FR angle $\alpha_{1}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HL angle $\alpha_{3}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, 'Lateral body velocity $-\mathbf{A}^{x}_{13}$', FontSize=fS);
    % %
    ax = nexttile(tl); % Ax for stance 24
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_24_X{i}, nAv_24_X{i}, ...
        "LineWidth", lW_Vector, "Color", col24s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FL angle $\alpha_{2}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HR angle $\alpha_{4}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, 'Lateral body velocity $-\mathbf{A}^{x}_{24}$', FontSize=fS);
    % %
    ax = nexttile(tl); % Ay for stance 13
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_13_Y{i}, nAv_13_Y{i}, ...
        "LineWidth", lW_Vector, "Color", col13s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FR angle $\alpha_{1}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HL angle $\alpha_{3}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, ...
        'Longitudinal body velocity $-\mathbf{A}^{y}_{13}$', FontSize=fS);
    % %
    ax = nexttile(tl); % Ay for stance 24
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_24_Y{i}, nAv_24_Y{i}, ...
        "LineWidth", lW_Vector, "Color", col24s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FL angle $\alpha_{2}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HR angle $\alpha_{4}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, ...
        'Longitudinal body velocity $-\mathbf{A}^{y}_{24}$', FontSize=fS);
    % %
    ax = nexttile(tl); % Atheta for stance 13
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_13_TH{i}, nAv_13_TH{i}, ...
        "LineWidth", lW_Vector, "Color", col13s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FR angle $\alpha_{1}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HL angle $\alpha_{3}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, ...
        'Rotational body velocity $-\mathbf{A}^{\theta}_{13}$', ...
        FontSize=fS);
    % %
    ax = nexttile(tl); % Atheta for stance 24
    quiver(ax, ...
        rad2deg(nalpha_x), rad2deg(nalpha_y), ...
        nAu_24_TH{i}, nAv_24_TH{i}, ...
        "LineWidth", lW_Vector, "Color", col24s);
    axis(ax, "equal"); ax.FontSize = fS;
    xlim(ax, angleLimits); ylim(ax, angleLimits);
    xticks(ax, angleTicks); yticks(ax, angleTicks);
    xlabel(ax, ...
        'FL angle $\alpha_{2}$ $({}^{\circ})$', ...
        FontSize=fS);
    ylabel(ax, ...
        'HR angle $\alpha_{4}$ $({}^{\circ})$', ...
        FontSize=fS);
    title(ax, ...
        'Rotational body velocity $-\mathbf{A}^{\theta}_{24}$', ...
        FontSize=fS);
end