% This function takes in a double array generated by vectorizing the output of the shape approximation function. This function DOESN'T HAVE INPUT CONCISTENCY
% CHECKS.
function out = cellappxshape(in)
    
    out = cell(size(in{1}, 1), 1);
    for i = 1:size(in{1}, 1)
        out{i} = in{1}(i, :);
    end

end