function [lvlsetVal, contourCoords] = contourArrToCells(contourArr)
%CONTOURARRTOCELLS Convert a contour array to cell arrays of the contour
%branches
%   The contour array is an array generated by any contour function like
%   contour, contourf, and contourc (only function that doesn't plot). This
%   array first column has the Z-levelset and number of rows in the current
%   branch and then has the contour coordinates to the right. This process
%   repeats with the next branch and so on. Our goal here is to extract
%   the branch coordinates alone and store it in separate arrays.

    % init the current array index location
    arrColIdx = 1;

    % init the output cell array
    contourCoords = cell(1, 0); lvlsetVal = cell(1, 0);

    % iterate in while loop and collect the branches
    while arrColIdx < size(contourArr, 2)
        
        % number of points in current branch
        currVal = contourArr(1, arrColIdx);
        currPts = contourArr(2, arrColIdx);

        % extract and assign the coordinates, and assign the level-set
        % values
        lvlsetVal{end+1} = currVal;
        contourCoords{end+1} = ...
            contourArr(:, arrColIdx + 1:arrColIdx + currPts);

        % increment to the next branch (or exit while loop)
        arrColIdx = arrColIdx + currPts + 1;

    end
    

end

