function hA = plot_SE2snapshot_QLvl2_clari_NoSlip(ax, pltTraj, F)
%PLOT_SE2SNAPSHOT_QLVL2_CLARI_NOSLIP animate the rigid quadrupedal robot given the trajectory structure
%   The trajectory structure needed to run this function is generated by "StitchQuadSE2gaits.m" and for example refer to "se2_GenericQuad_trot.mlx". The
%   plotting structure follows the general outline in "qlevel2noslip_mp.m". This function returns the plotted objects for deletion in the parent animation
%   function.

    % if the trajectory case is not provided
    if nargin < 3
        F = [1 pltTraj.dnum];
    end
    switch numel(F) ~= 2
        case 1
            error('ERROR! We need both the last frame and current frame to plot the body trajectory.');
        case 0
            fNoOld = F(1); fNo = F(2);
    end

    % Unpack everything needed plotting
    plot_info = pltTraj.plot_info;
    lW = plot_info.lW; 
    lW_s = plot_info.lW_s; lW_r = plot_info.lW_r;
    lW_qf = plot_info.lW_qf; lW_kq = plot_info.lW_kq;
    frame_scale = plot_info.frame_scale; circS = plot_info.circS;
    anim_lim = pltTraj.anim_lim;
    body_outline_x_t = pltTraj.body_outline_x_t; body_outline_y_t = pltTraj.body_outline_y_t;
    shape_outline_x_t = pltTraj.shape_outline_x_t; shape_outline_y_t = pltTraj.shape_outline_y_t;
    legs_x_t = pltTraj.legs_x_t; legs_y_t = pltTraj.legs_y_t;
    legsQ_x_t = pltTraj.legsQ_x_t; legsQ_y_t = pltTraj.legsQ_y_t; legsQ_u_t = pltTraj.legsQ_u_t; legsQ_v_t = pltTraj.legsQ_v_t;
    legsQ0_x_t = pltTraj.legsQ0_x_t; legsQ0_y_t = pltTraj.legsQ0_y_t; legsQ0_u_t = pltTraj.legsQ0_u_t; legsQ0_v_t = pltTraj.legsQ0_v_t;
    frame_x_t = pltTraj.frame_x_t; frame_y_t = pltTraj.frame_y_t; frame_u_t = pltTraj.frame_u_t; frame_v_t = pltTraj.frame_v_t;
    k_x_t = pltTraj.k_x_t; k_y_t = pltTraj.k_y_t;
    col_t = pltTraj.col_t; S = pltTraj.S;
    phi_tau = pltTraj.phi_tau; pbq = pltTraj.pbq; 
    x = pltTraj.x; y = pltTraj.y;
    
    % find the current config and snapshot points
    switch fNo == 1
        case 1
            idx = fNo;
        otherwise
            idx = [find(pbq(fNoOld:fNo-1)) + fNoOld-1, fNo];
    end

    % Initialize and start plotting ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    hA = cell(1, 0);
    m = 1;
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % plot the body trajectory (plotted first because latter plots stack on top) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    if (fNo ~= 1) % if not the first time step
        plotSeqSE2traj(ax, F, x, y, lW_s, phi_tau, col_t{7}, {pltTraj.alpha_body_t, pltTraj.alpha_body_nom});
    end
    if ~ishold(ax)
        hold on;
    end
    axis equal; axis(anim_lim);

    % plot body and limbs
    for k = idx
        switch k == fNo

            case 0 % not final frame-- just plot the shape outline

                % plot the shape outline
                plot(ax, shape_outline_x_t(:,k), shape_outline_y_t(:,k), ':', 'Color', col_t{5}(:,k), 'LineWidth', 0.25*lW);
                % plot the body axis frames
                quiver(ax, frame_x_t(:,k), frame_y_t(:,k), frame_scale*frame_u_t(:,k), frame_scale*frame_v_t(:,k), 'LineWidth', 0.25*lW_qf,...
                    'Color', col_t{5}(:,k),'LineStyle', '-',...
                    'AutoScale', 'off', 'ShowArrowHead', 'off');

            case 1 % final frame
                
                % plot the body and shape outlines
                if pbq(fNo) == 1
                    plot(ax, shape_outline_x_t(:,k), shape_outline_y_t(:,k), ':', 'Color', col_t{5}(:,k), 'LineWidth', 0.25*lW);           % ~deleted outline
                end
                hA{m}  = plot(ax, shape_outline_x_t(:,k), shape_outline_y_t(:,k), ':', 'Color', col_t{5}(:,k), 'LineWidth', 0.25*lW); m = m + 1;
                hA{m}  = plot(ax, body_outline_x_t(:,k), body_outline_y_t(:,k), '-', 'Color', col_t{5}(:,k), 'LineWidth', 0.25*lW); m = m + 1;      % outlines
                set(ax, 'xticklabel', []); set(ax, 'yticklabel', []); box("off");
                xline(ax, 0, ':', 'LineWidth', 0.5, 'Color', 'k');
                yline(ax, 0, ':', 'LineWidth', 0.5, 'Color', 'k');                                                      % define the origin
                for i = 1:4
                    hA{m}  = quiver(ax, legsQ_x_t(i,k), legsQ_y_t(i,k), legsQ_u_t(i,k), legsQ_v_t(i,k), 'Color', col_t{i}(:,k), 'LineWidth', lW, ...
                        'AutoScale', 'off', 'ShowArrowHead', 'off'); m = m + 1;                                         % leg i
                    % if ith limb is in the current contact state
                    if i == S(phi_tau(k), 1) || i == S(phi_tau(k), 2)
                        hA{m}  = quiver(ax, legsQ0_x_t(i,k), legsQ0_y_t(i,k), legsQ0_u_t(i,k), legsQ0_v_t(i,k), 'Color', col_t{i}(:,k), 'LineWidth', lW_r, ...
                        'LineStyle', '--', 'AutoScale', 'off', 'ShowArrowHead', 'off'); m = m + 1;                                         % leg i origin
                        hA{m}  = scatter(ax, legs_x_t(i,k), legs_y_t(i,k), circS, col_t{i}(:,k)', 'filled'); m = m + 1; % legtip i scatter
                    end
                end
                if pbq(fNo) == 1
                    quiver(ax, frame_x_t(:,k), frame_y_t(:,k), frame_scale*frame_u_t(:,k), frame_scale*frame_v_t(:,k), 'LineWidth', 0.25*lW_qf,...
                        'Color', col_t{5}(:,k),'LineStyle', '-','AutoScale', 'off', 'ShowArrowHead', 'off');
                end
                hA{m} = quiver(ax, frame_x_t(:,k), frame_y_t(:,k), frame_scale*frame_u_t(:,k), frame_scale*frame_v_t(:,k), 'LineWidth', 0.25*lW_qf,...
                        'Color', col_t{5}(:,k),'LineStyle', '-','AutoScale', 'off', 'ShowArrowHead', 'off'); m = m + 1;

                % plot the squared inter-leg distance
                % hA{m} = plot(ax, k_x_t{phi_tau(k)}(:,k), k_y_t{phi_tau(k)}(:,k), 'Color', col_t{6}(:,k), 'LineWidth', lW_kq, 'LineStyle', '--'); m = m + 1;

        end
    end


end

%% TRAJECTORY SEQUENTIAL PLOT FUNCTION
function plotSeqSE2traj(ax, F, x, y, lW_s, phi_tau, colS, ab)

    % unpack the previous frame and current frame
    fNoOld = F(1); % starting point
    fNo = F(2);    % end point
    ab_t = ab{1};
    ab_nom = ab{2};
    
    % find the points where the contact states change (adding 1 to shift it into the correct index because of diff, else it will be fNoOld-1)
    iShift = find(diff(phi_tau(fNoOld:fNo)) ~= 0) + fNoOld; 
    iShift(end+1) = fNo; % appending the current frame number to the end
    
    % Just iterate over every single trajectory point
    for i = 1:numel(iShift)

        % compute the starting and ending points of the current trajectory strip
        switch i
            case 1
                iStart = fNoOld; % the starting of a single cs trajectory (fNoOld)
            otherwise
                iStart = iEnd; % the last end point will be the current start point
        end
        iEnd = iShift(i); % the end point of a single cs trajectory

        % plot the trajectory chunk
        for j = iStart:iEnd-1
            plot(ax, x(j:j+1), y(j:j+1), 'LineWidth', 2*lW_s*ab_t(j)/ab_nom, 'Color', colS(:,iStart)); % scale the trajectory width proportional to the sprawl of the robot
            if j == 1 && ~ishold(ax)
                hold on; % hold all the plots
            end
        end

    end

end

