function plot_SE2snapshot_QLvl2_Rigid_NoSlip(traj)
%ANIMATEQLVL2_RIGID_NOSLIP animate the rigid quadrupedal robot given the trajectory structure
%   The trajectory structure needed to run this function is generated by "StitchQuadSE2gaits.m" and for example refer to "se2_GenericQuad_trot.mlx".



end

