function aViolation = ptViolatingFbounds_arbFormat...
    (aa_bX, aa_bY, aa, ll, gamma, ...
    F_fxn, F_bounds, F_bounds_full, ...
    refPt, delX, delY, ...
    ~, optLims)

    aViolation = [];

    [aLowViolation, fValViolation] = ...
    fmincon( @(a) abs(F_bounds(1) - ...
        FalongLine_arbFormat(aa_bX, aa_bY, aa, ll, gamma, ...
        F_fxn, refPt, [delX, delY], a)), ...
        optLims(1) + rand()*diff(optLims), ... % random IC
        [], [], [], [], ...
        optLims(1), optLims(2), ...
        [], ...
        optimoptions("fmincon", "Display", "off")... , "Algorithm", "sqp") ..., "OptimalityTolerance", 1e-8
            );
    if fValViolation < 1e-5*diff(F_bounds_full)
        aViolation = aLowViolation;
    else
        [aHighViolation, fValViolation] = ...
        fmincon( @(a) abs(F_bounds(2) - ...
            FalongLine_arbFormat(aa_bX, aa_bY, aa, ll, gamma, ...
            F_fxn, refPt, [delX, delY], a)), ...
            optLims(1) + rand()*diff(optLims), ...
            [], [], [], [], ...
            optLims(1), optLims(2), ...
            [], ...
            optimoptions("fmincon", "Display", "off")..., "Algorithm", "sqp") ..., "OptimalityTolerance", 1e-8
                );
        if fValViolation < 1e-5*diff(F_bounds_full)
            aViolation = aHighViolation;
        end
    end
end

